# Generated by Django 4.0.4 on 2022-06-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('publicate_year', models.IntegerField(null=True)),
                ('pages', models.IntegerField(null=True)),
                ('isbn_number', models.CharField(max_length=100, null=True)),
                ('language', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='')),
            ],
        ),
    ]
